# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  
  config.vm.define "testserver" do |node|
    node.vm.hostname = "testserver01"
    node.vm.box = "generic/rocky8"

    # Provider specific configuration
    node.vm.provider :libvirt do |domain|
      domain.management_network_mac = "52:54:00:00:01:01"
    
      # Provisioning configuration for Ansible.
        config.vm.provision "ansible" do |ansible|
        ansible.playbook = "playbook.yml"
      end
    end
  end  
end
