# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.hostname = "solr.test"
  config.ssh.insert_key = false

  #config.vm.define
  config.vm.provider :libvirt do |lv|
    lv.memory = 1024
    lv.management_network_mac = "52:54:00:00:01:01"
  end

  # Ansible provisioner.
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "playbook.yml"
  end
end
