---
- hosts: localhost
  become: yes

  tasks:
    - name: "Ensure Vagrant-Libvirt network is active"
      virt_net:
        command: define
        name: vagrant-libvirt
        xml: '{{ lookup("template", "vagrant-libvirt-net.xml") }}'
        state: present

    -name: "Start vagrant-libvirt network"
      virt_net:
        command: create
        name: vagrant-libvirt
        state: active
